%Curv_vals.mat

%This script takes the input frames and trial name for every roll documented and its
%corresponding CIthreshpts file generated by the curvature.m script to
%generate the mean, median, and mode of number of points over the CI
%threshold during each roll. It also calculates the roll duration and the
%rotational speed of each roll. It outputs a new spreadsheet with these
%values.

%%
% Read in file
data = xlsread('bendspeed.xlsx');

rolls = data(:,1);

processed = nan(length(data),5);
% Load in the CIthreshpts file
for n = length(rolls)
    r = load([rolls(n) '_CIthreshpts.mat']);
    
    %extract start and stop frames
    start = data(n,2);
    stop = data(n,3);
    
    %output the curvature mean, mode, and median for roll
    single = r(start:stop);
    single(single==0) = nan;
    
    mean = nanmean(single);
    mode = mode(single);
    median = mode(single,'omitnan');
    
    %output the roll duration and the rotational speed per roll
    frames = stop - start;
    rolldur = frames * 20 / 1000; %if 50 fps
    rotspeed = 1/rolldur; % 1/sec
    
    processed(n,1:5) = [mean mode median rolldur rotspeed];
end

%save as mat and xcel files
save('processed.mat','processed');
xlswrite('processed.xlsx','processed');
